version: "3"
services:
  postgres:
    image: postgres:13.4-alpine
    container_name: dogs-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dogs
    ports:
      - "35432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql